### ISSUE TITLE
Share: The Environment Setting of Assignment 3 in macOS

### ISSUE THREAD

**Issue by Shimingyi** [Shimingyi/COMP3360_Data_Driven_Animation#2]
Here I am sharing my experience with the installation of OpenGL Environment. 
If you meet any other errors with this one, please comment, and I will try to help; it will also help other students figure out their problems. 

Platform: macOS

## Main steps:
1. Install CMake and add it to PATH
2. Install Homebrew and glfw&glm library
3. Add extra files into the folder
4. Modify the cmake configuration file
5. Compile

### CMake installation 
Find the correct version and download it; there are a few things you need to do for using it: **download** -> **install** -> add it to **system path**

Download: [link](https://cmake.org/download/)

The system path configuration stores in different paths based on your shell language. If you use default bash, you should update `~/.bash_profile`; if you use zsh, you should update `~/.zshrc` or `~/.zsh_profile`. Add this line to the configuration file:
``` bash
export PATH="/Applications/CMake.app/Contents/bin:$PATH"
```
After the update, you should activate it and check if it works. 
``` bash
source ~/.zshrc
cmake --version
```

### Homebrew
Homebrew is a useful tool in macOS to manage the different libraries. You can find lots of documents to explain how it works and why we need it. Basically, you only need one line to install it: 
``` bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

And then, install glfw and glm:
``` bash
brew install glfw
brew install glm
```

After the installation, you should check if they are in these folder: 
``` bash
M1 chip:
/opt/homebrew/Cellar/glfw
/opt/homebrew/Cellar/glm

Intel chip:
/usr/local/Cellar/glfw
/usr/local/Cellar/glm
```

(If you were using Intel Mac previously, and now you transferred the original data to M1 mac, it will make some conflicts. I suggest you reinstall Homebrew. refer: [link](https://github.com/Homebrew/discussions/discussions/417))

### Adding extra files
Except for these two libraries, you should also include another folder called KHR in the project folder. The code can be found [here](https://github.com/chitalu/glfw-project/tree/main/KHR). 
``` bash
- pba_tutorial1_rbd
        - KHR
                - khrplatform.h
        ...
        - main.cpp
        ...
```

### Modify the cmake configuration file
Then you can update the CMakeLists.txt with this new information, notice the path of glfw and glm will be replaced with the path in your machine:
``` cmake
cmake_minimum_required(VERSION 2.8.11) 

set (proj_name rigid-body-dynamics)

project(${proj_name} C CXX)               

set(CMAKE_CXX_STANDARD 11)  

file(GLOB HEADER_FILES *.h)
file(GLOB SRC_FILES *.c *.cpp)

add_executable(${proj_name} ${SRC_FILES} ${HEADER_FILES})

target_compile_definitions(
  ${proj_name} 
  PRIVATE 
  -DPROJECT_ROOT_DIR="${CMAKE_CURRENT_SOURCE_DIR}"
  -DPROJECT_NAME_STR="${proj_name}")

find_package(OpenGL REQUIRED)

target_include_directories(
  ${proj_name} 
  PRIVATE
  /opt/homebrew/Cellar/glfw/3.3.6/include
  /opt/homebrew/Cellar/glm/0.9.9.8/include
  ${CMAKE_SOURCE_DIR} 
  ${OPENGL_INCLUDE_DIR} 
  )

target_link_libraries(
  ${proj_name} 
  /opt/homebrew/Cellar/glfw/3.3.6/lib/libglfw.3.3.dylib
  ${OPENGL_gl_LIBRARY} 
  ${CMAKE_DL_LIBS} )
```

### Compile
Open terminal and navigate to the project folder, run following commands:
``` bash
mkdir build 
cd build
cmake ..
make
```
Then you will find an execution file in the build folder. 

Expected output: 
``` bash
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rubbly/Library/CloudStorage/OneDrive-Personal/Onedrive-文档/Courses/TA-computer-animation/project/pba_tutorial1_rbd/build


[ 20%] Building CXX object CMakeFiles/rigid-body-dynamics.dir/gl_utils.cpp.o
[ 40%] Building C object CMakeFiles/rigid-body-dynamics.dir/glad.c.o
[ 60%] Building CXX object CMakeFiles/rigid-body-dynamics.dir/main.cpp.o
[ 80%] Building CXX object CMakeFiles/rigid-body-dynamics.dir/trimesh.cpp.o
[100%] Linking CXX executable rigid-body-dynamics
[100%] Built target rigid-body-dynamics
```

**Comment by shwnyao** [comment]
I had a `library not found for -lglfw` issue when trying to compile the project when my glfw is installed with HomeBrew on macOS with m1 chip,

and was able to resolve the issue by adding the following lines to the file `~/.zshrc`
```
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
```
