### ISSUE TITLE
Share: The Environment Setting of Assignment 3 in Windows

### ISSUE THREAD

**Issue by Shimingyi** [Shimingyi/COMP3360_Data_Driven_Animation#3]
Here I am sharing my experience with the installation of OpenGL environment. 
If you meet any other errors with this one, pls comment and I will try to help, it will also help other students to figure out their problems. 

Platform: Windows 11

## Main steps:
1. Install MinGW and CMAKE, and add it to system environment. 
2. Add extra libraries on the folder 
3. Modify the cmake configuration file
4. Compile

### 1. MinGW and CMAKE installation 

What is MinGW? You can find the official wiki [here](https://en.wikipedia.org/wiki/MinGW). In a simple word, it's the windows-version GCC, which can compile your c/cpp code in windows environment. 

There are a few things you need to do for using it, **download** -> **install** -> and add it into your **system environment**.  

MinGW  Download: [link](https://sourceforge.net/projects/mingw-w64/files/mingw-w64/)
![image](https://user-images.githubusercontent.com/7709951/160443638-6c59994e-9572-4b02-9b48-609a8c4e5f63.png)

MinGW system environment: [guide](https://thegeekpage.com/environment-variables-in-windows-11/)
![image](https://user-images.githubusercontent.com/7709951/160444429-0e30abe7-18ec-4c9b-817f-9195723a476a.png)

For CMAKE, the steps are same, you should  **download** -> **install** -> and add it into your **system environment**.  

CMAKE Download: [link](https://cmake.org/download/)
System environment:
![image](https://user-images.githubusercontent.com/7709951/160445042-adb7d735-6139-4d32-9db7-d65f67ee50c3.png)

After your configuration, you need to restart your PC and active the new setting. And then, make sure they can be found in Windows terminal.
``` bash
gcc --version
cmake --version
```
![image](https://user-images.githubusercontent.com/7709951/160445602-c99d011b-68ed-49d6-84a7-88fd431e9924.png)

### 2. Extra library

There are three extra libraries should be included in this project.
* [KHR](https://github.com/chitalu/glfw-project/tree/main/KHR) folder from glad library
* [extern/glfw](https://github.com/glfw/glfw/tree/7d5a16ce714f0b5f4efa3262de22e4d948851525)
* [extern/glm](https://github.com/g-truc/glm/tree/bf71a834948186f4097caa076cd2663c69a10e1e)

Download/git clone them, then have an folder arrangement based on the [recommendation](https://github.com/chitalu/glfw-project).
``` bash
- pba_tutorial1_rbd
        - KHR
                - khrplatform.h
        - extern
                - glfw
                - glm
        ...
        - main.cpp
        ...
``` 

### 3. cmake configuration 
Update the whole CMakeLists.txt file based on the new provided one: [CMakeLists.txt](https://github.com/chitalu/glfw-project/blob/main/CMakeLists.txt)
``` cmake
cmake_minimum_required( VERSION 3.1 )

project( glfw-project )

find_package( OpenGL REQUIRED )

include_directories( ${OPENGL_INCLUDE_DIRS} )

set( GLFW_BUILD_DOCS OFF CACHE BOOL  "GLFW lib only" )
set( GLFW_INSTALL OFF CACHE BOOL  "GLFW lib only" )
set( GLFW_BUILD_EXAMPLES OFF CACHE BOOL  "GLFW lib only" )
set( GLFW_BUILD_TESTS OFF CACHE BOOL  "GLFW lib only" )

add_subdirectory( extern/glfw )

if( MSVC )
    SET( CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /ENTRY:mainCRTStartup" )
endif()

set(CMAKE_CXX_STANDARD 11)  

file(GLOB HEADER_FILES *.h)
file(GLOB SRC_FILES *.c *.cpp)
     
add_executable( glfw-project WIN32 ${HEADER_FILES} ${SRC_FILES})

target_compile_definitions(
    glfw-project 
  PRIVATE 
    -DPROJECT_ROOT_DIR="${CMAKE_CURRENT_SOURCE_DIR}"
    -DPROJECT_NAME_STR="glfw-project")

target_link_libraries( glfw-project ${OPENGL_LIBRARIES} glfw )

#
# add extra include directories e.g. "glm" here
#
target_include_directories(glfw-project PRIVATE extern/glm ${CMAKE_CURRENT_SOURCE_DIR})

if( MSVC )
    if(${CMAKE_VERSION} VERSION_LESS "3.6.0") 
        message( "\n\t[ WARNING ]\n\n\tCMake version lower than 3.6.\n\n\t - Please update CMake and rerun; OR\n\t - Manually set 'glfw-project' as StartUp Project in Visual Studio.\n" )
    else()
        set_property( DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT glfw-project )
    endif()
endif()
```

### 4. Compile
Open terminal and navigate to the project folder, run following commands:
``` bash
mkdir build
cd build
cmake -G"MinGW Makefiles" ..
cmake --build .    # or: mingw32-make
```
Then you will find an execution file in the build folder. 

Expected output:
```bash
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: E:/Libs/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: E:/Libs/mingw64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: opengl32
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for dinput.h
-- Looking for dinput.h - found
-- Looking for xinput.h
-- Looking for xinput.h - found
-- Performing Test _GLFW_HAS_DEP
-- Performing Test _GLFW_HAS_DEP - Success
-- Performing Test _GLFW_HAS_ASLR
-- Performing Test _GLFW_HAS_ASLR - Success
-- Performing Test _GLFW_HAS_64ASLR
-- Performing Test _GLFW_HAS_64ASLR - Success
-- Using Win32 for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Downloads/COMP3360_Data_Driven_Animation-main/COMP3360_Data_Driven_Animation-main/pba_tutorial1_rbd/build


[  4%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/context.c.obj
[  9%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/init.c.obj
[ 14%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/input.c.obj
[ 19%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/monitor.c.obj
[ 23%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/vulkan.c.obj
[ 28%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/window.c.obj
[ 33%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/win32_init.c.obj
[ 38%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/win32_joystick.c.obj
[ 42%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/win32_monitor.c.obj
[ 47%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/win32_time.c.obj
[ 52%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/win32_thread.c.obj
[ 57%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/win32_window.c.obj
[ 61%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/wgl_context.c.obj
[ 66%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/egl_context.c.obj
[ 71%] Building C object extern/glfw/src/CMakeFiles/glfw.dir/osmesa_context.c.obj
[ 76%] Linking C static library libglfw3.a
[ 76%] Built target glfw
[ 80%] Building CXX object CMakeFiles/glfw-project.dir/gl_utils.cpp.obj
[ 85%] Building C object CMakeFiles/glfw-project.dir/glad.c.obj
[ 90%] Building CXX object CMakeFiles/glfw-project.dir/main.cpp.obj
[ 95%] Building CXX object CMakeFiles/glfw-project.dir/trimesh.cpp.obj
[100%] Linking CXX executable glfw-project.exe
[100%] Built target glfw-project

```

**Comment by chitalu** [comment]
Hi @Shimingyi,

Thanks for providing the extra information. I would like to add a little more, which will likely be easier:

An updated list of instructions (for those working on Windows) can be found on the GitHub course page [here](https://github.com/Shimingyi/COMP3360_Data_Driven_Animation). Refer to the README file and under the section "Physics-based animation tutorials", which has a new note detailing how you can build tutorial 1 and 2 on Windows.

Students do not necessarily need to use a Windows virtual machine (VM), Cygwin or MinGW. A VM was used during the class demonstration as a quick guide showing how to setup your tutorial project on any Windows device. 

If users on Mac are facing similar issues, they can following these same steps I have outlined here.

I hope this information is useful.

Best,
Floyd
